{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.extraLabels}}
    {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "gateway.selectorLabelsPods" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    {{- toYaml .Values.podMonitor.endpoints | nindent 4 }}
  {{- with .Values.podMonitor.attachMetadata }}
  attachMetadata:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.podMonitor.bodySizeLimit }}
  bodySizeLimit: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.convertClassicHistogramsToNHCB }}
  convertClassicHistogramsToNHCB: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.fallbackScrapeProtocol }}
  fallbackScrapeProtocol: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.jobLabel }}
  jobLabel: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.keepDroppedTargets }}
  keepDroppedTargets: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.labelLimit }}
  labelLimit: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.labelNameLengthLimit }}
  labelNameLengthLimit: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.labelValueLengthLimit }}
  labelValueLengthLimit: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.nativeHistogramBucketLimit }}
  nativeHistogramBucketLimit: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.nativeHistogramMinBucketFactor }}
  nativeHistogramMinBucketFactor:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.podMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.podMonitor.sampleLimit }}
  sampleLimit: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.scrapeClass }}
  scrapeClass: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.scrapeClassicHistograms }}
  scrapeClassicHistograms: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.scrapeProtocols }}
  scrapeProtocols: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.selectorMechanism }}
  selectorMechanism: {{ . }}
  {{- end }}
  {{- with .Values.podMonitor.targetLimit }}
  targetLimit: {{ . }}
  {{- end }}
{{- end }}
