{{- if .Values.redirectHTTP }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "gateway.fullname" . }}-redirect-http
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "gateway.fullname" . }}
    sectionName: http
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end}}
