apiVersion: v2
name: security-apps
description: Argo CD app-of-apps config for security applications
type: application
version: 0.127.0
home: https://github.com/adfinis/helm-charts/tree/main/charts/security-apps
sources:
  - https://github.com/adfinis/helm-charts
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: |
        Updated Secrets Store CSI Driver chart from 1.5.6 to 1.6.0, including:
          - Chart update from 1.5.6 to 1.6.0
          - Support for Kubernetes v1.33
          - CSI Driver image update to v1.5.4
          - Bug fixes, dependency updates, and Helm chart maintenance improvements
      links:
        - name: "Secrets Store CSI Driver chart 1.6.0"
          url: https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v1.6.0
        - name: "Secrets Store CSI Driver chart 1.5.6"
          url: https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v1.5.4
