apiVersion: v2
name: security-apps
description: Argo CD app-of-apps config for security applications
type: application
version: 0.122.0
home: https://github.com/adfinis/helm-charts/tree/main/charts/security-apps
sources:
  - https://github.com/adfinis/helm-charts
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: |
        feat: Update Kyverno from 1.17.1 to 1.18.1

        - Secure HTTP calls with blocklist/allowlist
        - Namespaced image registry credentials
        - CLI expanded policy support
        - Success event filtering
        - Update Helm chart from 3.7.1 to 3.8.1
        - Many more fixes and improvements in both the app and chart
      links:
        - name: Kyverno 1.18.0
          url: https://github.com/kyverno/kyverno/releases/tag/v1.18.0
        - name: Kyverno 1.18.1
          url: https://github.com/kyverno/kyverno/releases/tag/v1.18.1
