{{- if .Values.keycloak.oidcclients.enabled }}
{{- $fullname := include "keycloak-operator.fullname" . }}
{{- $labels := include "keycloak-operator.labels" . }}
{{- range .Values.keycloak.oidcclients.clients }}
---
apiVersion: k8s.keycloak.org/v2beta1
kind: KeycloakOIDCClient
metadata:
  name: {{ $fullname }}-{{ .realm }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  keycloakCRName: {{ default $fullname .keycloakCRName }}
  realm: {{ .realm | quote }}
  client:
    {{- .client | toYaml | nindent 4 }}
{{- end }}
{{- end }}
