{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bbook.fullname" . }}-secret
  labels:
    {{- include "bbook.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ include "bbook.databasePassword" . | b64enc }}
  OIDC_CLIENT_SECRET: {{ .Values.config.oidc.clientSecret | b64enc }}
  SESSION_SECRET: {{ .Values.config.sessionSecret | b64enc }}
  {{- if .Values.config.zoho.syncEnabled }}
  ZOHO_CLIENT_ID: {{ .Values.config.zoho.clientID | b64enc }}
  ZOHO_CLIENT_SECRET: {{ .Values.config.zoho.clientSecret | b64enc }}
  ZOHO_REFRESH_TOKEN: {{ .Values.config.zoho.refreshToken | b64enc }}
  {{- end }}
{{- end }}
