apiVersion: v2
name: logging-apps
description: Argo CD app-of-apps config for logging applications
type: application
version: 0.50.0
home: https://github.com/adfinis/helm-charts/tree/main/charts/logging-apps
sources:
  - https://github.com/adfinis/helm-charts
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: |
        Updated Fluent Bit to 0.57.9, including:
          - Update Fluent Bit OCI image from v5.0.3 to v5.0.9
          - Includes Fluent Bit image updates v5.0.4 through v5.0.9
      links:
        - name: "Fluent Bit Helm chart changelog"
          url: https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/CHANGELOG.md
