apiVersion: v2
name: gateway
description: Chart for a kgateway gateway

type: application

version: 0.1.0

# Supported version of kgateway
appVersion: "v2.2.2"

maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com

dependencies:
- name: opentelemetry-collector
  version: "0.127.2"
  repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  condition: otelcol.enabled
  alias: otelcol

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "feat: add gateway chart"
      links:
        - name: Github PR
          url: https://github.com/adfinis/helm-charts/pull/1770
