apiVersion: v2
name: misc-apps
description: Argo CD app-of-apps config for miscellaneous small tools
type: application
version: 0.70.0
home: https://github.com/adfinis/helm-charts/tree/main/charts/misc-apps
sources:
  - https://github.com/adfinis/helm-charts
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: changed
      description: |
        Deprecate grafanaAgentOperator as it is deprecated upstream.
        Update grafanaAgentOperator to its last release (chart 0.5.2).
      links:
        - name: Last release and depreciation notice
          url: https://github.com/grafana/agent/releases/tag/v0.44.3
