apiVersion: v2
name: misc-apps
description: Argo CD app-of-apps config for miscellaneous small tools
type: application
<<<<<<< HEAD
version: 0.69.0
=======
version: 0.67.0
>>>>>>> 5b45867 (fix: chart version)
home: https://github.com/adfinis/helm-charts/tree/main/charts/misc-apps
sources:
  - https://github.com/adfinis/helm-charts
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: |
        Update reloader chart from 2.2.8 to 2.2.11
        * Bumped dependencies
      links:
        - name: reloader 2.2.11 chart release
          url: https://github.com/stakater/Reloader/releases/tag/chart-v2.2.11
        - name: reloader 2.2.10 chart release
          url: https://github.com/stakater/Reloader/releases/tag/chart-v2.2.10
        - name: reloader 2.2.9 chart release
          url: https://github.com/stakater/Reloader/releases/tag/chart-v2.2.9
