apiVersion: v2
name: misc-apps
description: Argo CD app-of-apps config for miscellaneous small tools
type: application
version: 0.68.0
home: https://github.com/adfinis/helm-charts/tree/main/charts/misc-apps
sources:
  - https://github.com/adfinis/helm-charts
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: |
        Update keda from 2.18.1 to 2.19.0
        * replace kube-rbac-proxy with native secure metrics
        * add k8s networkPolicy
        * release http-add-on
      links:
        - name: KEDA Chart v2.19.0 release
          url: https://github.com/kedacore/charts/releases/tag/v2.19.0
