name: Release Charts

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      pages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup environment for release
        run: hack/ci/github/setup/release.sh

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.14.0

      - name: Add dependency chart repos
        run: yq e '."chart-repos"[]' hack/chart-testing/ct.yaml | tr "=" " " | xargs -L1 helm repo add

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          # Allow us to re-run the release action
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"

      - name: Run gomplate to update pages index
        run: hack/ci/github/steps/update-page.sh
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
