apiVersion: v2
name: argo-apps
description: Argo CD app-of-apps config for various argo project components
type: application
version: 0.29.0
home: https://github.com/adfinis/helm-charts/tree/main/charts/argo-apps
sources:
  - https://github.com/adfinis/helm-charts
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: |
        Update Argo Rollouts from 1.8.3 to 1.8.4

        * Updated dependencies
        * fix: bluegreen analysis prematurely succeeds if new ReplicaSet becomes unsaturated
      links:
        - name: Release notes
          url: https://github.com/argoproj/argo-rollouts/releases/tag/v1.8.4
